export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SUCCESS_MESSAGE_CLEAR = 'SUCCESS_MESSAGE_CLEAR';
export const ERROR_MESSAGE_CLEAR = 'ERROR_MESSAGE_CLEAR';